// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_node.proto

package github.com.crazyStrongboy.node;

public interface SyncResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:data_node.SyncResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string version = 1;</code>
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 1;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
