// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_node.proto

package github.com.crazyStrongboy.node;

public interface SyncRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:data_node.SyncRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string apply = 1;</code>
   */
  java.lang.String getApply();
  /**
   * <code>string apply = 1;</code>
   */
  com.google.protobuf.ByteString
      getApplyBytes();
}
