// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_node.proto

package github.com.crazyStrongboy.node;

public final class TestNodes {
  private TestNodes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_node_SyncRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_node_SyncRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_node_SyncResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_node_SyncResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017test_node.proto\022\tdata_node\"\034\n\013SyncRequ" +
      "est\022\r\n\005apply\030\001 \001(\t\"\037\n\014SyncResponse\022\017\n\007ve" +
      "rsion\030\001 \001(\t2L\n\017DataSyncService\0229\n\004sync\022\026" +
      ".data_node.SyncRequest\032\027.data_node.SyncR" +
      "esponse\"\000B9\n\036github.com.crazyStrongboy.n" +
      "odeB\tTestNodesP\001\242\002\tETESTNODEb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_data_node_SyncRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_data_node_SyncRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_node_SyncRequest_descriptor,
        new java.lang.String[] { "Apply", });
    internal_static_data_node_SyncResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_data_node_SyncResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_node_SyncResponse_descriptor,
        new java.lang.String[] { "Version", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
