// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_node_stream.proto

package github.com.crazyStrongboy.stream;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:data_node.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string send = 1;</code>
   */
  java.lang.String getSend();
  /**
   * <code>string send = 1;</code>
   */
  com.google.protobuf.ByteString
      getSendBytes();
}
