// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_node_stream.proto

package github.com.crazyStrongboy.stream;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:data_node.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string receive = 1;</code>
   */
  java.lang.String getReceive();
  /**
   * <code>string receive = 1;</code>
   */
  com.google.protobuf.ByteString
      getReceiveBytes();
}
