// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_node_stream.proto

package github.com.crazyStrongboy.stream;

public final class TestNodeStreams {
  private TestNodeStreams() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_node_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_node_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_node_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_node_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026test_node_stream.proto\022\tdata_node\"\035\n\rS" +
      "treamRequest\022\014\n\004send\030\001 \001(\t\"!\n\016StreamResp" +
      "onse\022\017\n\007receive\030\001 \001(\t2W\n\rStreamService\022F" +
      "\n\tstreamRpc\022\030.data_node.StreamRequest\032\031." +
      "data_node.StreamResponse\"\000(\0010\001BB\n github" +
      ".com.crazyStrongboy.streamB\017TestNodeStre" +
      "amsP\001\242\002\nETESTNODESb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_data_node_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_data_node_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_node_StreamRequest_descriptor,
        new java.lang.String[] { "Send", });
    internal_static_data_node_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_data_node_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_node_StreamResponse_descriptor,
        new java.lang.String[] { "Receive", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
